### ISSUE TITLE
Sql Lite

### ISSUE THREAD

**Issue by estebanbacl** [katorres02/tuaplicaciontest#1]
https://github.com/katorres02/tuaplicaciontest/blob/8d234996fd8245cc70318257b8016604f6c4f500/config/environments/test.rb#L1

Luego de correr la creación de la base de datos y las migraciones, encontré que no se encuentra el archivo "database.yml" dentro de la configuración del proyecto, luego de seguir con las instrucciones del readme.md, que configuración se realiza apara ejecutar el proyecto con base de datos sql lite.

**Comment by katorres02** [comment]
Hola @estebanbacl normalmente agrego el database.yml al gitignore. Para este proyecto se puede usar el database.yml estandar de rails que se conecta con sqlite3

**/config/database.yml**
```ruby
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
```

Lo primero que podrías hacer es crear un usuario con el servicio post que allí se explica, luego podrías autenticarte usando el login y generarle "intereses" o editar información que quieras.

Toda la información almacenada la puedes ver en el dashboard, solo deberías recargar el dashboard ``http://localhost:3000``

Saludos

**Comment by estebanbacl** [comment]
Perfecto @katorres02 el proyecto corre.
